name: Next.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          version: "latest"
      - run: bun install
      - name: Build
        run: bun run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: desk-calendar-app
          path: out/
          overwrite: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: desk-calendar-app
          path: dist
      - name: Display downloaded files
        run: ls -R dist/
      - name: Deploy to FTP server
        uses: atssj/gh-actions/actions/ftp-deploy@main
        with:
          ftp_server_name: ${{ secrets.FTP_SERVER_NAME_DCA }}
          ftp_server_username: ${{ secrets.FTP_SERVER_USERNAME_DCA }}
          ftp_server_password: ${{ secrets.FTP_SERVER_PASSWORD_DCA }}
          ftp_server_port: 21
          input_dir: dist/
          remote_dir: desk-calendar-app/
